SPKPRODUKT-33340: release og publiser vha manuell workflow (#3)

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -1,28 +1,113 @@
-name: Build and Publish to GitHub Packages
+name: Tag a release and publish artifacts if needed
 
 on:
   push:
     branches:
       - main
 
-jobs:
-  release-and-publish-npm:
-    uses: statens-pensjonskasse/public-actions-library/.github/workflows/build-library-node.yaml@b1509281d74a1afb44d9ceabfb361f8cf4bec420 # v0.3.6
-    permissions:
-      contents: write
-      packages: write
-    secrets: inherit
-    with:
-      node-version: '24'
+permissions:
+  contents: write
 
-  publish-mvn:
+env:  # TODO: just use npm for versioning
+  API_SPEC_FILE: skatt-inntekt-api.yaml
+
+jobs:
+  release:
     runs-on: ubuntu-latest
-    if: needs.release-and-publish-npm.outputs.published == 'true'
+    outputs:
+      version: ${{ steps.apiversion.outputs.apiversion }}
+      release: ${{ steps.goahead.outputs.release }}
+
     steps:
       - name: Checkout
         uses: actions/checkout@v4
         with:
-          ref: ${{ github.event.release.tag_name }}
+          fetch-depth: 0
+
+      - name: Find last release tag
+        id: gitversion
+        run: |
+          git fetch --tags
+          LAST_GIT_TAG=$(git tag --sort=-v:refname | head -n1)
+          if [ -z "$LAST_GIT_TAG" ]; then
+            LAST_RELEASE_VERSION="0.0.0"
+          else
+            LAST_RELEASE_VERSION=$(echo "$LAST_GIT_TAG" | awk -F. '{print $1 "." $2 "." $3+1}')
+          fi
+          echo "gitversion=$LAST_RELEASE_VERSION" >> $GITHUB_OUTPUT
+
+      - name: Find spec version
+        id: apiversion
+        run: |
+          API_VERSION=$(awk -F': *' '/^[[:space:]]*version:[[:space:]]*/ {print $2; exit}' "$API_SPEC_FILE" | tr -d '"' | tr -d "'" | xargs)
+          if [ -z "$API_VERSION" ]; then
+            echo "::error::Could not read version from $API_SPEC_FILE"
+            exit 1
+          fi
+          echo "apiversion=$API_VERSION" >> $GITHUB_OUTPUT
+
+      - name: Determine need for release by comparing spec version to last git version tag, abort if they are the same
+        id: goahead
+        run: |
+          if [ "${{ steps.apiversion.outputs.apiversion }}" = "${{ steps.gitversion.outputs.gitversion }}" ]; then
+            echo "::info::Terminate release because $API_SPEC_FILE version ${{ steps.apiversion.outputs.apiversion }} is same as git version ${{ steps.gitversion.outputs.gitversion }}."
+            echo "release=false" >> "$GITHUB_OUTPUT"
+            exit 0
+          fi
+          echo "release=true" >> "$GITHUB_OUTPUT"
+
+      - name: Update version in package.json, commit and push
+        run: |
+          git config user.name github-actions
+          git config user.email github-actions@github.com
+
+          # tagging is done by release step below
+          git tag ${{ needs.versioning.outputs.version }}
+          git push origin ${{ needs.versioning.outputs.version }}
+
+      - name: Generate app token for release
+        id: app-token
+        uses: actions/create-github-app-token@v3
+        if: 'TODO: har ikke tilgang til PUBLIC_ACTIONS_LIBRARY_APP_ID og PUBLIC_ACTIONS_LIBRARY_SSH_KEY' == 'true'
+        with:
+          client-id: ${{ secrets.GH_ACTIONS_LIBRARY_APP_ID }}
+          private-key: ${{ secrets.GH_ACTIONS_LIBRARY_APP_KEY }}
+
+      - name: Create Release
+        uses: softprops/action-gh-release@v2
+        with:
+          tag_name: ${{ needs.versioning.outputs.version }}
+          generate_release_notes: true
+        env:
+          GITHUB_TOKEN: ${{ github.token }}
+
+  publish-npm:
+    runs-on: ubuntu-latest
+    needs: [ release ]
+    if: needs.release.outputs.release == 'true'
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+      - name: Setup Node
+        uses: actions/setup-node@v4
+        with:
+          node-version: 24
+          registry-url: https://npm.pkg.github.com
+      - name: Publish npm package
+        id: publish
+        env:
+          NODE_AUTH_TOKEN: ${{ github.token }}
+        run: |
+          npm publish
+          echo "published=true" >> "$GITHUB_OUTPUT"
+
+  publish-mvn:
+    runs-on: ubuntu-latest
+    needs: [ release ]
+    if: needs.release.outputs.release == 'true'
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
       - name: Set up JDK
         uses: actions/setup-java@v5
         with:
